[include]
files = [
  "keybinds.toml",
  "outputs.toml",
]

[general]
autostart = [
  "noctalia",
]
mod_key = "Super"
xwayland = true
focus_on_activate = false

[appearance]
prefer_no_csd = true
border_width = 0
outer_border_width = 0
corner_radius = 0

[overview]
background_blur = false
zoom = 0.15
shortcut_keys = "invbwruo"

#[animation]
#enabled = false

[input.touchpad]
natural_scroll = true

[input.cursor]
theme = "Bibata-Modern-Classic"
size = 24
hide_when_typing = true
hide_timeout_ms = 1000

[input.mouse]
accel_profile = "flat"
sensitivity = -0.4

[layout]
mode = "scrolling"
gap = 0
